//Assignment no 16:

function Add() {
    // Addition is a way of combining things and counting them together as one large group
    var num1 = 10;
    var num2=10;
    document.getElementById("id1").innerHTML = num1+ num2;
}
// Assignment no 17:
function Subtract() {
    // In math, to subtract means to take away from a group or a number of things
    var num1 = 5;
    var num2=1;
    document.getElementById("id2").innerHTML = num1+num2;
}

// Assignment no 18:

function Multiply() {
    // Multiplication (often denoted by the cross symbol ×, by the mid-line dot operator ⋅, by juxtaposition, or, on computers, by an asterisk *)
    var num1 = 6;
    var num2=6;
    document.getElementById("id3").innerHTML =num1*num2;
}

// Assignment no 19:

function multipleOperations(){
    // Division, Multiplication, Addition and Subtraction (DMAS) is the elementary rule for the order of operation of the Binary operations.
    var outcome = (10-3) + (5*2) /2;
    document.getElementById("more_Maths").innerHTML = outcome;
}

// Assignment no 20:
function mod_Operation(){
    // Modular arithmetic, sometimes called clock arithmetic, is a calculation that involves a number that resets itself to zero each time a whole number greater than 1, which is the mod, is reached. 
    var outcome = 20 % 2;
    document.getElementById("mod").innerHTML = outcome;
}

// Assignment no 21:

function unary(){
    // A unary operation is an operation with only one operand. This operand comes either before or after the operator. 
    var num1 = 20;
    document.getElementById("id4").innerHTML =num1;
}


// Assignment no 22:

function Increment(){
    // What is increment (++) operator in JavaScript? The increment operator increases an integer value by one.
    var num1 = 40;
    document.getElementById("Increment").innerHTML = ++num1;
}
function Decrement(){
    // JavaScript Decrement (-–) Arithmetic Operator is used to decrement the given number by one.
    var num2 = 40;
    document.getElementById("Decrement").innerHTML = --num2;
}

// Assignment no 23:

function randomNumber(){
    // A number generated by a process, whose outcome is unpredictable is called Random Number.
    document.getElementById("id5").innerHTML = Math.random()*1000;
}

